<!-- Type:Dip -->

# Hummus

\begin{recipe}{Classic Hummus}{a lot}{20 minutes (after chickpeas are cooked)}
\ingredient[1]{lb.}{Dried Chick Peas (gabanzo beans)}
\ingredient[1/2]{tsp}{baking soda}
Soak the chickpeas for at least eight hours in advance. I usually put them in water to soak in the morning and the make the hummus in the evening. If you forget to soak, you can quick soak by brining the beans to a boil, then letting them sit for about an hour, drain the water and then cook them.

After the chickpeas are soaked, drain the water and add new water and the baking soda (this helps make thm soft). If you have a pressure cooker, pressure cook for 20 minutes. You want the chickpeas to be really soft for a creamy hummus. If you don't have a pressure cooker, just boil them until they are really soft (could take an hour or so).

\ingredient [1/2]{cup}{lemon juice}
\ingredient[3]{cloves}{garli}
Squeeze 1 or 2 lemons to produce 1/2 cup of lemon juice. Then press the garlic into the lemon juice and let it sit for a few minutes (go on to the next steps in the mean time). Doing this retains the garlic flavor, but removes the bite of raw garlic.

\ingredient[3/4]{cup}{tahini}
\ingredient[1/4]{cup}{olive oil}
\ingredient[1.5]{Tablespoon}{Cumin}
\ingredient[2.5]{Teaspoon}{salt}
\ingredient[1/2]{Teaspoon}{garlic powder}
Drain the cooked chickpeas, but keep some of the water in a boal. You might need it later. Also set aside a few whole chickpeas for garnish (around 20).
Add the chickpeas, tahini, olive oil, lemon juice, garlic, cumin, salt and garlic powder to a food processor or blender. Blend until smooth. If, needed, add some of the cooked chickpea water to make it smoother. 

\ingredient[a few]{sprinkles}{Paprika}
Put the hummus in a bowl. Garnish with a few sprinkles of paprika, the few whole chickpeaks, and a drizzle of olive oil if you want. You can also garnish with zaatar if you have it and/or parsley.

Enjoy with you favorite dipee! (thing you dip in a dip)


\end{recipe}
